#!/bin/bash
set -e

cd $(dirname $0)/..

: ${CONFIG:=$(pwd)/config}
: ${ARCH:='amd64 arm'}

./scripts/download

for arch in $ARCH; do
  ./scripts/build-busybox-static ${CONFIG}/${arch}/buildroot-config-static ${CONFIG}/busybox-ps-modprobe-only.config
  ./scripts/package ${arch}
done
