#!/bin/bash
set -e

cd $(dirname $0)/..

: ${ARTIFACTS:=$(pwd)/assets}
: ${BUILD:=$(pwd)/build}

busybox_install()
{
    local conf=$1
    local bbconf=$2

    mkdir -p ${BUILD}
    cd ${BUILD}

    local buildroot=$(ls -1 ${ARTIFACTS}/buildroot-*.tar.bz2)

    if [ ! -e "${buildroot}" ]; then
        echo "Failed to find busybox archive, found : ${buildroot}" 1>&2
        return 1
    else
        buildroot=$(basename $buildroot)
    fi

    rm -rf ${buildroot/.tar.bz2//}
    tar xvjf ${ARTIFACTS}/${buildroot}
    cd ${buildroot/.tar.bz2//}

    cp $conf .config
    if [ -n "$bbconf" ]; then
        cp $bbconf package/busybox/
    fi
    make oldconfig
    make
}

busybox_install "$1" "$2"
