#!/bin/bash
set -e
set -x

cd $(dirname $0)/..

: ${ARTIFACTS:=$(pwd)/assets}

check()
{
    local hash=$1
    local file=$2

    if [ ! -e "$file" ]; then
        return 1
    fi

    CURRENT=$(sha1sum $file | awk '{print $1}')

    [ "$hash" = "$CURRENT" ]
}

download()
{
    mkdir -p ${ARTIFACTS}

    local url=$2
    local file=${ARTIFACTS}/$(basename $2)
    local hash=$1

    if ! check $hash $file; then
        curl -sL $url > $file
    fi

    if ! check $hash $file; then
        echo "ERROR: $file does not match checksum $hash, got $CURRENT" 1>&2
        return 1
    fi
}

download a267a1fd403df2c3ac8b756ed03ab162ffac21e8 https://buildroot.org/downloads/buildroot-2015.11.1.tar.bz2
