#!/bin/bash
set -ex

cd $(dirname $0)/..

arch="$1"

rm -rf build
mkdir -p build

cp /etc/ssl/certs/ca-certificates.crt ./build/
cp ./assets/base-files_${arch}.tar.gz ./build/base-files.tar.gz
tar -xf ./assets/docker-$(echo $DOCKER_VERSION | sed -e 's/^v//')_${arch}.tgz -C ./build --strip-components=1

strip_bin=$(which strip)
if [ "${arch}" == "arm" ]; then
  export GOARM=6
  export CGO_ENABLED=1
  export CC=/usr/bin/arm-linux-gnueabihf-gcc
  strip_bin=/usr/bin/arm-linux-gnueabihf-strip
fi
if [ "${arch}" == "arm64" ]; then
  export GOARM=
  export CGO_ENABLED=1
  export CC=/usr/bin/aarch64-linux-gnu-gcc
  strip_bin=/usr/bin/aarch64-linux-gnu-strip
fi

GOARCH=${arch} go build -ldflags "-linkmode external -extldflags -static" -o build/dockerlaunch ./main
${strip_bin} --strip-all build/dockerlaunch
