#!/bin/bash
set -x

cd $(dirname $0)/..

: ${ARTIFACTS:=$(pwd)/assets}

check()
{
    local hash=$1
    local file=$2

    if [ ! -e "$file" ]; then
        return 1
    fi

    CURRENT=$(sha1sum $file | awk '{print $1}')

    [ "$hash" = "$CURRENT" ]
}

download()
{
    mkdir -p ${ARTIFACTS}

    local url=$2
    local file=${ARTIFACTS}/$(basename $2)
    local hash=$1

    if ! check $hash $file; then
        curl -sL $url > $file
    fi

    if ! check $hash $file; then
        echo "ERROR: $file does not match checksum $hash, got $CURRENT" 1>&2
        return 1
    fi
}

if [ -e base-image/dist/base-files.tar.gz ]; then
    cp base-image/dist/base-files.tar.gz build/
else
    download HASH http://
fi

download 386f6e91114dc252a13b266fe2ac3a27e83bd0f7 https://get.docker.com/builds/Linux/x86_64/docker-1.7.1

cp assets/docker-* build/docker
chmod +x build/docker
