#!/bin/bash
set -e

cd $(dirname $0)/..

. ./scripts/common

cp assets/base-files_amd64.tar.gz build/base-files.tar.gz
cp assets/docker build/docker

docker build -t $IMAGE -f Dockerfile .

echo Built $IMAGE
